#!/bin/sh

case $1 in
	start)
		echo `date` "HelloWorldPhp is installed properly & started" >> /var/log/MODS_HelloWorld_CGI;
		exit 0
	;;
	stop)
    echo `date` "HelloWorldPhp is stopped" >> /var/log/MODS_HelloWorld_CGI;
		exit 0
	;;
	status)
		exit 0
	;;
	log)
		echo /var/log/MODS_HelloWorld_CGI;
		exit 0
	;;
esac