#!/bin/sh

LOG="/var/log/MODS_FlexTV"
ERRLOG="/var/log/MODS_FlexTV_ERR"
if [[ -f "$ERRLOG" ]]; then
  rm -f "$ERRLOG"
fi

#close the stream and redirect them to a custom or standard Syno Log
exec 1<&-
exec 2<&-
exec 1>>$LOG
exec 2>>$ERRLOG

echo `date` "POST UPGRADE PKG VERSION: $SYNOPKG_PKGVER"

cp $SYNOPKG_TEMP_UPGRADE_FOLDER/configBKP/*.php /var/services/web/FlexTV/php/config/

if [ -s "$ERRLOG" ]; then
  echo `date` "----------------------------------------------------"
  cat $ERRLOG
  echo `date` "----------------------------------------------------"
  # make the log pretty to be displayed by the Catalog Manager
  echo `date` "Prettifying the POST UPGRADE log file"
  sed -i 's/$/<br>/' "$ERRLOG"
  cat $ERRLOG >> $SYNOPKG_TEMP_LOGFILE
  exit 1
fi

exit 0