#!/bin/sh

LOG="/var/log/MODS_FlexTV"
ERRLOG="/var/log/MODS_FlexTV_ERR"
if [[ -f "$ERRLOG" ]]; then
  rm -f "$ERRLOG"
fi

#close the stream and redirect them to a custom or standard Syno Log
exec 1<&-
exec 2<&-
exec 1>>$LOG
exec 2>>$ERRLOG

#if [[ "$SYNOPKG_PKG_STATUS" == "INSTALL" ]]; then

echo `date` "POST INSTALL PKG VERSION: $SYNOPKG_PKGVER"

chown -R http "$SYNOPKG_PKGDEST/ui/FlexTV"

if [[ -d "/var/services/web/FlexTV" ]]; then
    COUNT=$(ls -dq /var/services/web/FlexTV.* | wc -l)
    mv "/var/services/web/FlexTV" "/var/services/web/FlexTV.$COUNT"
fi

mv "$SYNOPKG_PKGDEST/ui/FlexTV" "/var/services/web/FlexTV"

if [ -s "$ERRLOG" ]; then
  echo `date` "----------------------------------------------------"
  cat $ERRLOG
  echo `date` "----------------------------------------------------"
  # make the log pretty to be displayed by the Catalog Manager
  echo `date` "Prettifying the POST INSTALL log file"
  sed -i 's/$/<br>/' "$ERRLOG"
  cat $ERRLOG >> $SYNOPKG_TEMP_LOGFILE
  exit 1
fi

#fi

exit 0