#!/bin/sh
MYSQL=`which mysql`;

echo $pkgwizard_admin_password > $$
pkgwizard_admin_password=`sed 's/"/\\"/gp' $$`
/bin/rm -f $$

Q1="CREATE DATABASE IF NOT EXISTS $pkgwizard_db_Name COLLATE = utf8_unicode_ci;"
Q2="GRANT USAGE ON *.* TO $pkgwizard_srvmon_account@localhost IDENTIFIED BY '$pkgwizard_srvmon_password';"
Q3="GRANT ALL PRIVILEGES ON $pkgwizard_db_Name.* TO $pkgwizard_srvmon_account@localhost;"
Q4="GRANT ALL PRIVILEGES ON $pkgwizard_db_Name.* TO $SYNOPKG_USERNAME@localhost;"
Q5="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}${Q4}${Q5}"

RESULT=`$MYSQL -h "$pkgwizard_server_name" -u "$pkgwizard_admin_account" --password="$pkgwizard_admin_password" --skip-column-names -e "SHOW DATABASES LIKE '$pkgwizard_db_Name'"`
if [ "$RESULT" == "$pkgwizard_db_Name" ]; then
    echo "Existing database $pkgwizard_db_Name is going to be reused" > $SYNOPKG_TEMP_LOGFILE
    exit 0
fi

$MYSQL -vvv -h "$pkgwizard_server_name" -u "$pkgwizard_admin_account" --password="$pkgwizard_admin_password" -e "$SQL"
if [ $? -eq 1 ]; then
    if [ -z "$SYNOPKG_DSM_LANGUAGE" ]; then
        echo "Fail to create $pkgwizard_db_Name  database." > $SYNOPKG_TEMP_LOGFILE
        exit 0
    fi
    case $SYNOPKG_DSM_LANGUAGE in
         *)
        echo "Fail to create $pkgwizard_db_Name database." > $SYNOPKG_TEMP_LOGFILE 
         ;;
    esac
    exit 0
fi

exit 0