#!/bin/sh

. `dirname $0`/common `basename $0` $*

StartScript

UnlinkNginx "$MODS_ADMIN" "$MODS_PASSWORD" "$MODS_PORT"
ExitCode=$?

EndScript

if [ $ExitCode == "0" ]; then
    exit 0
else
    exit 150
fi