#!/bin/sh
CONFIG="/var/packages/$SYNOPKG_PKGNAME"
if [ ! -d "$CONFIG/etc" ]; then
    mkdir "$CONFIG/etc"
fi
echo "$pkgwizard_hello" > $CONFIG/etc/pkgwizard_hello


# set the name of the package in the nginx config and router.cgi
sed -i -e "s|@MODS_CGI@|$SYNOPKG_PKGNAME|g" "$SYNOPKG_PKGDEST/ui/dsm.cgi.conf"
sed -i -e "s|@SYNOPKG_PKGNAME@|$SYNOPKG_PKGNAME|g" "$SYNOPKG_PKGDEST/ui/router.cgi"

# link the nginx config to redirect pages accessed on admin port
rm -f /usr/syno/share/nginx/conf.d/dsm.$SYNOPKG_PKGNAME.conf
ln -s $SYNOPKG_PKGDEST/ui/dsm.cgi.conf /usr/syno/share/nginx/conf.d/dsm.$SYNOPKG_PKGNAME.conf
#sudo synoservicecfg --reload nginx
. `dirname $0`/trace `basename $0` $*
