#!/bin/sh
case $1 in
	start)		
		. `dirname $0`/trace `basename $0` $*
		exit 0
	;;
	stop)
		. `dirname $0`/trace `basename $0` $*
		exit 0
	;;
	status)
		if [ true ]; then
			if [ ! -f "$SYNOPKG_PKGDEST/request_status_ok" ]; then
				touch "$SYNOPKG_PKGDEST/request_status_ok"
				. `dirname $0`/trace `basename $0` $*
			fi
			exit 0
		else
			if [ ! -f "$SYNOPKG_PKGDEST/request_status_ko" ]; then
				touch "$SYNOPKG_PKGDEST/request_status_ko"
				. `dirname $0`/trace `basename $0` $*
			fi
			exit 150 # package is broken and should be reinstalled
		fi
	;;
	log)
		if [ ! -f "$SYNOPKG_PKGDEST/request_log" ]; then
			touch "$SYNOPKG_PKGDEST/request_log"
			. `dirname $0`/trace `basename $0` $*
		fi
		echo "/var/log/$SYNOPKG_PKGNAME.log"
		exit 0
	;;
    *)
        exit 1
    ;;	
esac
