#!/bin/sh
MYSCRIPT=$(basename "$0")
MYPKG=$(dirname "$0")
MYPKG=$(dirname "$MYPKG")
MYPKG=$(basename "$MYPKG")
# change /usr/syno/synoman/scripts/ext-3.4-compatible-6.x/ back to /usr/syno/synoman/scripts/ext-3/
if [ -n "$SYNOPKG_DSM_VERSION_MAJOR" ] && [ "$SYNOPKG_DSM_VERSION_MAJOR" -lt 7 ] ; then
	sed -i -e "s~/ext-3.4-compatible-6.x/~/ext-3/~g" /var/packages/"$MYPKG"/target/ui/page.html
fi

exit 0
