#!/bin/sh

LOG="/var/log/MODS_FlexTV"
ERRLOG="/var/log/MODS_FlexTV_ERR"
if [[ -f "$ERRLOG" ]]; then
  rm -f "$ERRLOG"
fi

#close the stream and redirect them to a custom or standard Syno Log
exec 1<&-
exec 2<&-
exec 1>>$LOG
exec 2>>$ERRLOG

if [[ "$SYNOPKG_PKG_STATUS" == "INSTALL" ]]; then

echo `date` "POST INSTALL PKG VERSION: $SYNOPKG_PKGVER"

ETC_DIR="/var/packages/$SYNOPKG_PKGNAME/etc"

# set the name of the package in the nginx config and router.cgi
sed -i -e "s|@MODS_CGI@|$SYNOPKG_PKGNAME|g" "$SYNOPKG_PKGDEST/ui/dsm.cgi.conf"
sed -i -e "s|@SYNOPKG_PKGNAME@|$SYNOPKG_PKGNAME|g" "$SYNOPKG_PKGDEST/ui/router.cgi"

# copy the router.cgi into the website
cp "$SYNOPKG_PKGDEST/ui/router.cgi" "$SYNOPKG_PKGDEST/ui/FlexTV/"

# link the nginx config to redirect pages accessed on admin port
rm -f /usr/syno/share/nginx/conf.d/dsm.$SYNOPKG_PKGNAME.conf
ln -s $SYNOPKG_PKGDEST/ui/dsm.cgi.conf /usr/syno/share/nginx/conf.d/dsm.$SYNOPKG_PKGNAME.conf
sudo synoservicecfg --reload nginx


if [ -s "$ERRLOG" ]; then
  echo `date` "----------------------------------------------------"
  cat $ERRLOG
  echo `date` "----------------------------------------------------"
  # make the log pretty to be displayed by the Catalog Manager
  echo `date` "Prettifying the POST INSTALL log file"
  sed -i 's/$/<br>/' "$ERRLOG"
  cat $ERRLOG >> $SYNOPKG_TEMP_LOGFILE
  exit 1
fi

fi

chown -R http "$SYNOPKG_PKGDEST/ui"

exit 0