#!/bin/sh
LOG="/var/log/$SYNOPKG_PKGNAME"_INS
ERRLOG="/var/log/$SYNOPKG_PKGNAME"_ERR
if [[ -f "$ERRLOG" ]]; then
  rm -f "$ERRLOG"
fi

# Close the streams and redirect them to custom Logs
exec 1<&-
exec 2<&-
exec 1>>$LOG
exec 2>>$ERRLOG

# Log the name of the current script, its parameters and the version of the package
echo `date` "["`basename $0`"] [$*] PKG VERSION: $SYNOPKG_PKGVER"

#---------------------------------------------------------------------------------------------------
# ADD YOU CODE HERE UNDER

# set the name of the package in the nginx config
sed -i -e "s|@MODS_CGI@|$SYNOPKG_PKGNAME|g" "$SYNOPKG_PKGDEST/ui/dsm.cgi.conf"

# link the nginx config to redirect pages accessed on admin port
rm -f /usr/syno/share/nginx/conf.d/dsm.$SYNOPKG_PKGNAME.conf
ln -s $SYNOPKG_PKGDEST/ui/dsm.cgi.conf /usr/syno/share/nginx/conf.d/dsm.$SYNOPKG_PKGNAME.conf
#sudo synoservicecfg --reload nginx [done via package config]



# END YOUR CODE HERE ABOVE
#---------------------------------------------------------------------------------------------------

if [ -s "$ERRLOG" ]; then
  echo `date` "----------------------------------------------------"
  cat $ERRLOG
  echo `date` "----------------------------------------------------"
  # Make the log pretty to be displayed by the Catalog Manager
  sed -i 's/$/<br>/' "$ERRLOG"
  # Return the error log to the Catalog Manager
  cat $ERRLOG >> $SYNOPKG_TEMP_LOGFILE
  exit 1
fi

# Return a message for the user via the Catalog Manager
echo "Post installation done<br>" >> $SYNOPKG_TEMP_LOGFILE

exit 0