#!/bin/sh

. `dirname $0`/common `basename $0` $*

StartScript
if [ $? != 0 ]; then
    exit 150
fi

LinkNginx "`whoami`"
ExitCode=$?

if [ $ExitCode == "0" ]; then
    EnableRouterLog
fi

EndScript
if [ $ExitCode == "0" ]; then
    exit 0
else
    exit 150
fi