#!/bin/sh
LOG="/var/log/$SYNOPKG_PKGNAME"

case $1 in
  start)
    echo `date` "MODS Package Capture is installed properly & started" >> $LOG
    exit 0
    ;;
  stop)
    echo `date` "MODS Package Capture cannot be stopped" >> $LOG		
    exit 0
    ;;
  status)
    exit 0
    ;;
  log)
    exit 0
    ;;
esac

exit 0