#!/bin/sh
ETC=/var/packages/phpMyAdmin/target/synology_added/etc/

rm -rf /var/services/web/phpMyAdmin
mv /var/packages/phpMyAdmin/target/phpMyAdmin /var/services/web/phpMyAdmin

ln -sf /var/packages/phpMyAdmin/target/www.phpMyAdmin.disabled.conf /usr/local/etc/nginx/conf.d/

# generate a random blowfish_secret encryption key
if [ "$SYNOPKG_PKG_STATUS" = "UPGRADE" ]; then
    blowfish_secret=$(cat /tmp/pMA.upgrade)
else
    blowfish_secret=$(/usr/bin/openssl rand -base64 32)
fi
sed -i "s|__BLOWFISH_SECRET__|$blowfish_secret|" "/var/services/web/phpMyAdmin/config.inc.php"
mkdir -p /usr/syno/etc/packages/phpMyAdmin/nginx

/usr/bin/php -d open_basedir="$ETC" "$ETC"/serverconfcommon INIT
[ -f /var/packages/MariaDB/enabled ] && /usr/bin/php -d open_basedir="$ETC" "$ETC"/serverconfcommon ADDM5
[ -f /var/packages/MariaDB10/enabled ] && /usr/bin/php -d open_basedir="$ETC" "$ETC"/serverconfcommon ADDM10

exit 0
