#!/bin/sh

SZD_PMA="/var/packages/phpMyAdmin"
DESKTOP="/usr/syno/synoman/webman/3rdparty/phpMyAdmin"
phpMyAdminTarget="${SZD_PMA}/target"
phpMyAdminUI="${phpMyAdminTarget}/ui"
DSM_INDEX_ADD="/usr/syno/bin/pkgindexer_add"
DSM_INDEX_DEL="/usr/syno/bin/pkgindexer_del"
WEBDIR="/var/services/web/phpMyAdmin"
NGINX_CONF_DIR="/usr/local/etc/nginx/conf.d/"
NGINX_ENALBE_CONF="www.phpMyAdmin.enable.conf"
NGINX_DISABLE_CONF="www.phpMyAdmin.disabled.conf"

ReturnBroken() {
	exit 150
}

StartDaemons() {
	rm -f $DESKTOP
	if [ -d "$WEBDIR" ]; then
		ln -sf ${phpMyAdminUI} ${DESKTOP}
		${DSM_INDEX_ADD} ${phpMyAdminUI}/index.conf
	else
		echo "web/phpMyAdmin not found."> $SYNOPKG_TEMP_LOGFILE
		ReturnBroken
	fi

	rm -rf ${NGINX_CONF_DIR}/${NGINX_DISABLE_CONF}
	ln -sf ${phpMyAdminTarget}/synology_added/${NGINX_ENALBE_CONF} ${NGINX_CONF_DIR}
}

StopDaemons()
{
	${DSM_INDEX_DEL} ${phpMyAdminUI}/index.conf
	rm -f ${DESKTOP}

	rm -rf ${NGINX_CONF_DIR}/${NGINX_ENALBE_CONF}
	ln -sf ${phpMyAdminTarget}/synology_added/${NGINX_DISABLE_CONF} ${NGINX_CONF_DIR}
}
case "$1" in
	start)
		StartDaemons
		;;
	stop)
		StopDaemons
		;;
	restart)
		StopDaemons
		sleep 1
		StartDaemons
		;;
	status)
		if [ ! -d "/var/services/web/phpMyAdmin" ]; then
			rm -f $DESKTOP
			ReturnBroken
		fi
		exit 0
		;;
	log)
		LOGFILE="/tmp/phpMyAdmin.log"
		grep "phpMyAdmin:" /var/log/messages > ${LOGFILE}
		if [ $? -eq 0 ]; then
			echo "${LOGFILE}"
		fi
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status|log}" >&2
		exit 1
		;;
esac

exit 0

