#!/bin/sh
LOG="/var/log/$SYNOPKG_PKGNAME"
echo `date` $SYNOPKG_PKGNAME "V"$SYNOPKG_PKGVER "is post-installing" >> $LOG

ERRLOG="$LOG"_ERR
rm -f "$ERRLOG"

#close the streams and redirect them to a custom or standard Syno Log
exec 1<&-
exec 2<&-
exec 1>>$LOG
exec 2>>$ERRLOG

echo "pkgwizard_keepData = $pkgwizard_keepData";

if [ "$pkgwizard_keepData" == "false" ]; then
  rm -R /usr/syno/etc/packages/$SYNOPKG_PKGNAME
fi

if [ -f "$SYNOPKG_PKGDEST/../etc/webfolder" ]; then
  pkgwizard_webFolder=`cat "$SYNOPKG_PKGDEST/ui/Acpi_On_Lan/config/webfolder"`
  if [ -n "$pkgwizard_webFolder" && -L "/var/services/web/$pkgwizard_webFolder" ]; then
    rm -f "/var/services/web/$pkgwizard_webFolder"
  fi
fi

rm -f /usr/syno/share/nginx/conf.d/dsm.$SYNOPKG_PKGNAME.conf

if [ -s "$ERRLOG" ]; then
  echo `date` "----------------------------------------------------"
  cat $ERRLOG
  echo `date` "----------------------------------------------------"
  # make the log pretty to be displayed by the Catalog Manager
  echo `date` "Prettifying the POST INSTALL log file"
  sed -i 's/$/<br>/' "$ERRLOG"
  cat $ERRLOG >> $SYNOPKG_TEMP_LOGFILE
  exit 1
fi

exit 0