#!/bin/sh
LOG="/var/log/$SYNOPKG_PKGNAME"
echo `date` $SYNOPKG_PKGNAME "V"$SYNOPKG_PKGVER "is post-installing" >> $LOG

ERRLOG="$LOG"_ERR
rm -f "$ERRLOG"

#close the streams and redirect them to a custom or standard Syno Log
exec 1<&-
exec 2<&-
exec 1>>$LOG
exec 2>>$ERRLOG

echo `date` "Granting access on log files for the webserver"
chmod o+w $LOG
chmod o+w $ERRLOG

chown -R http "$SYNOPKG_PKGDEST/ui"

# set the name of the package in the nginx config and router.cgi
sed -i -e "s|@MODS_CGI@|$SYNOPKG_PKGNAME|g" "$SYNOPKG_PKGDEST/ui/dsm.cgi.conf"
sed -i -e "s|@SYNOPKG_PKGNAME@|$SYNOPKG_PKGNAME|g" "$SYNOPKG_PKGDEST/ui/router.cgi"

#link the nginx config to redirect pages accessed on admin port
rm -f /usr/syno/share/nginx/conf.d/dsm.$SYNOPKG_PKGNAME.conf
ln -s $SYNOPKG_PKGDEST/ui/dsm.cgi.conf /usr/syno/share/nginx/conf.d/dsm.$SYNOPKG_PKGNAME.conf

#restating nginx is done via package's dependencies (instuninst_restart_services)
#sudo synoservicecfg --reload nginx

ln -s /usr/syno/etc/packages/$SYNOPKG_PKGNAME $SYNOPKG_PKGDEST/ui/Acpi_On_Lan/config
chown http /usr/syno/etc/packages/$SYNOPKG_PKGNAME
if [ -n "$pkgwizard_tokenVendor" ]; then
  echo "$pkgwizard_tokenVendor" > $SYNOPKG_PKGDEST/ui/Acpi_On_Lan/config/token
fi
chmod +s /usr/bin/ping

if [ -s "$ERRLOG" ]; then
  echo `date` "----------------------------------------------------"
  cat $ERRLOG
  echo `date` "----------------------------------------------------"
  # make the log pretty to be displayed by the Catalog Manager
  echo `date` "Prettifying the POST INSTALL log file"
  sed -i 's/$/<br>/' "$ERRLOG"
  cat $ERRLOG >> $SYNOPKG_TEMP_LOGFILE
  exit 1
fi

exit 0