#!/bin/sh
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

### This script will be executed when package uninstalled and upgraded.
### Actions before package uninstalled
### ex. backup package data.

exit 0
