#!/bin/sh
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

### This script will execute ONLY before package upgrade
### Actions before package upgraded.
### ex. backup user settings for package upgrade.

exit 0
