#!/bin/sh
LOG="/var/log/$SYNOPKG_PKGNAME"
echo `date` $SYNOPKG_PKGNAME "V"$SYNOPKG_PKGVER "is post-uninstalling" >> $LOG

rm -f /usr/syno/share/nginx/conf.d/dsm.$SYNOPKG_PKGNAME.conf

#restating nginx is done via package's dependencies (instuninst_restart_services)
#sudo synoservicecfg --reload nginx

exit 0