#!/bin/sh
LOG="/var/log/$SYNOPKG_PKGNAME"
case $1 in
  start)
    echo `date` $SYNOPKG_PKGNAME "V"$SYNOPKG_PKGVER "is installed properly & started" >> $LOG
    exit 0
    ;;
  stop)
    echo `date` "----------------------------------------------------"
    echo `date` $SYNOPKG_PKGNAME "V" $SYNOPKG_PKGVER "is stopped" >> $LOG
    exit 0
    ;;
  status)
    exit 0
    ;;
  log)
    echo $LOG
    exit 0
    ;;
esac