#!/bin/sh
LOG=/var/log/MODS_WebConsole
case $1 in
  start)
    echo `date` "MODS Web Console is installed properly & started" >> $LOG
    exit 0
    ;;
  stop)
    echo `date` "MODS Web Console is stopped" >> $LOG
    exit 0
    ;;
  status)
    exit 0
    ;;
  log)
    echo $LOG
    exit 0
    ;;
esac